const menuData = {
  hot: [
    { ar: 'اسبريسو سينجل', en: 'Single Espresso', cal: '10-20', price: 8 },
    { ar: 'اسبريسو دبل', en: 'Double Espresso', cal: '5-10', price: 10 },
    { ar: 'قهوة اليوم', en: "Today's Coffee", cal: '5-15', price: 7 },
    { ar: 'لاتيه', en: 'Latte', cal: '120-170', price: 13 },
    { ar: 'كابيتشينو', en: 'Cappuccino', cal: '100-150', price: 13 },
    { ar: 'فلات وايت', en: 'Flat White', cal: '120-160', price: 13 },
    { ar: 'كورتادو', en: 'Cortado', cal: '60-80', price: 12 },
    { ar: 'امريكانو', en: 'Americano', cal: '10-20', price: 9 },
    { ar: 'كراميل ماكياتو', en: 'Caramel Macchiato', cal: '220-280', price: 14 },
    { ar: 'سبانيش لاتيه', en: 'Spanish Latte', cal: '220-300', price: 14 },
    { ar: 'بيستاشيو لاتيه', en: 'Pistachio Latte', cal: '250-320', price: 15 },
    { ar: 'وايت موكا', en: 'White Mocha', cal: '250-320', price: 14 },
    { ar: 'V60', en: 'V60', cal: '5-15', price: 11 },
    { ar: 'ماتشا', en: 'Matcha', cal: '200-260', price: 14 },
    { ar: 'سولتد كراميل', en: 'Salted Caramel', cal: '250-330', price: 15 },
    { ar: 'هوت شوكليت', en: 'Hot Chocolate', cal: '280-350', price: 12 },
    { ar: 'قهوه تركي', en: 'Turkish Coffee', cal: '30-50', price: 8 },
    { ar: 'قهوه فرنساوي', en: 'French Coffee', cal: '180-220', price: 10 },
    { ar: 'شاي انجليزي أحمر', en: 'English Red Tea', cal: '0-5', price: 4 },
    { ar: 'شاي انجليزي أخضر', en: 'English Green Tea', cal: '0-5', price: 4 },
    { ar: 'شاي', en: 'Tea', cal: '0-5', price: 3 },
    { ar: 'شاي حليب', en: 'Tea With Milk', cal: '120-180', price: 4 },
    { ar: 'ينسون', en: 'Anise', cal: '0-5', price: 4 },
    { ar: 'سحلب', en: 'Sahlab', cal: '180-240', price: 10 },
    { ar: 'زنجبيل', en: 'Ginger', cal: '130-190', price: 5 },
    { ar: 'زنجبيل حليب', en: 'Ginger With Milk', cal: '0-5', price: 6 },
    { ar: 'زنجبيل ليمون', en: 'Ginger With Lemon', cal: '5-10', price: 5 },
    { ar: 'قرفة', en: 'Cinnamon', cal: '0-5', price: 5 },
    { ar: 'كركديه', en: 'Hibiscus', cal: '40-60', price: 5 },
  ],
  cold: [
    { ar: 'ايس لاتيه', en: 'Ice Latte', cal: '120-170', price: 13 },
    { ar: 'ايس أمريكانو', en: 'Ice Americano', cal: '10-20', price: 9 },
    { ar: 'ايس سيجنتشر لاتيه', en: 'Ice Signature Latte', cal: '180-320', price: 15 },
    { ar: 'ايس بيستاشيو لاتيه', en: 'Ice Pistachio Latte', cal: '250-320', price: 15 },
    { ar: 'ايس شيكن نجمة حور', en: 'Ice Shaken Nijma Hour', cal: '280-350', price: 16 },
    { ar: 'ايس وايت موكا', en: 'Iced White Mocha', cal: '250-330', price: 14 },
    { ar: 'ماتشا بارد', en: 'Cold Matcha', cal: '220-300', price: 15 },
    { ar: 'ايس V60', en: 'Iced V60', cal: '300-380', price: 11 },
    { ar: 'ايس كراميل ماكياتو', en: 'Iced Caramel Macchiato', cal: '100-140', price: 14 },
    { ar: 'موكا فرابتشينو', en: 'Mocha Frappuccino', cal: '100-140', price: 14 },
    { ar: 'قهوه بالكراميل', en: 'Caramel Coffee', cal: '280-350', price: 16 },
    { ar: 'كراميل فرابتشينو', en: 'Caramel Frappuccino', cal: '110-150', price: 14 },
    { ar: 'موهيتو فراولة', en: 'Strawberry Mojito', cal: '110-150', price: 13 },
    { ar: 'موهيتو ليمون نعناع', en: 'Lemon Mint Mojito', cal: '158', price: 13 },
    { ar: 'موهيتو خوخ', en: 'Peach Mojito', cal: '146', price: 13 },
    { ar: 'موهيتو توت', en: 'Berry Mojito', cal: '186', price: 13 },
    { ar: 'موهيتو رمان', en: 'Pomegranate Mojito', cal: '80-120', price: 13 },
    { ar: 'موهيتو باشن فروت', en: 'Passion Fruit Mojito', cal: '156', price: 13 },
    { ar: 'موهيتو كود رد', en: 'Code Red Mojito', cal: '0', price: 17 },
    { ar: 'كركديه بارد', en: 'Iced Hibiscus', cal: '40-60', price: 5 },
    { ar: 'مياه', en: 'Water', cal: '0', price: 1 },
  ],
  juices: [
    { ar: 'مانجو', en: 'Mango', cal: '150-180', price: 14 },
    { ar: 'فراولة', en: 'Strawberry', cal: '120-150', price: 14 },
    { ar: 'برتقال', en: 'Orange', cal: '110-140', price: 11 },
    { ar: 'أفوكادو', en: 'Avocado', cal: '220-280', price: 15 },
    { ar: 'بينا كولادا - أناناس جوز الهند', en: 'Pina Colada', cal: '180-220', price: 16 },
    { ar: 'بطيخ', en: 'Watermelon', cal: '150-170', price: 10 },
    { ar: 'موز حليب', en: 'Banana With Milk', cal: '80-110', price: 11 },
    { ar: 'ليمون نعناع', en: 'Mint Lemon', cal: '220-280', price: 11 },
    { ar: 'كركديه', en: 'Hibiscus', cal: '100-140', price: 10 },
  ],
  soda: [
    { ar: 'كينزا كولا', en: 'Kinza Cola', cal: '157', price: 4 },
    { ar: 'كينزا برتقال', en: 'Kinza Orange', cal: '6', price: 4 },
    { ar: 'كينزا حمضيات', en: 'Kinza Citrus', cal: '61', price: 4 },
    { ar: 'بيبسي', en: 'Pepsi', cal: '156', price: 5 },
    { ar: 'بيبسي دايت', en: 'Diet Pepsi', cal: '0', price: 5 },
    { ar: 'ديو', en: 'Duet', cal: '158', price: 5 },
    { ar: 'ميراندا', en: 'Mirinda', cal: '179', price: 5 },
    { ar: 'حمضيات', en: 'Citrus', cal: '179', price: 5 },
    { ar: 'سفن أب', en: '7Up', cal: '157', price: 5 },
    { ar: 'سفن أب دايت', en: 'Diet 7Up', cal: '6', price: 5 },
    { ar: 'كود رد', en: 'Code Red', cal: '61', price: 7 },
    { ar: 'موسي شعير', en: 'Barley Moussy', cal: '17', price: 8 },
    { ar: 'موسي رمان', en: 'Pomegranate Moussy', cal: '40', price: 8 },
    { ar: 'موسي تفاح', en: 'Apple Moussy', cal: '19', price: 8 },
    { ar: 'موسي ليمون نعناع', en: 'Lemon Mint Moussy', cal: '39', price: 8 },
    { ar: 'مياه', en: 'Water', cal: '0', price: 1 },
  ],
  sweets: [
    { ar: 'كرواسون جبنة شيدر', en: 'Cheddar Croissant', cal: '345', price: 5 },
    { ar: 'كرواسون ساده', en: 'Plain Croissant', cal: '305', price: 5 },
    { ar: 'كرواسون زعتر', en: 'Thyme Croissant', cal: '345', price: 5 },
    { ar: 'كرواسون شيكولاته', en: 'Chocolate Croissant', cal: '370', price: 5 },
    { ar: 'تشيز كيك', en: 'Cheese Cake', cal: '350-410', price: 15 },
    { ar: 'كوكيز فانيليا', en: 'Vanilla Cookies', cal: '650-725', price: 8 },
    { ar: 'كوكيز شيكولاته', en: 'Chocolate Cookies', cal: '389', price: 8 },
    { ar: 'مافن شيكولاته', en: 'Chocolate Muffin', cal: '350-450', price: 8 },
    { ar: 'مافن توت ازرق', en: 'Blueberry Muffin', cal: '350-450', price: 8 },
    { ar: 'سلطة فواكه', en: 'Fruit Salad', cal: '120-200', price: 13 },
    { ar: 'آيس كريم', en: 'Ice Cream', cal: '150-250', price: 10 },
    { ar: 'أم علي', en: 'Om Ali', cal: '218', price: 12 },
    { ar: 'أرز بحليب', en: 'Milk Rice', cal: '320', price: 10 },
    { ar: 'وافل', en: 'Waffle', cal: '350-410', price: 16 },
    { ar: 'بان كيك', en: 'Pancake', cal: '90-100', price: 15 },
    { ar: 'كريب حلو', en: 'Sweet Crepe', cal: '300-500', price: 16 },
    { ar: 'حلي كاسات اوريو', en: 'Oreo Cups', cal: '420-480', price: 10 },
    { ar: 'حلي كاسات نوتيلا', en: 'Nutella Cups', cal: '430-500', price: 10 },
    { ar: 'حلي كاسات العسل', en: 'Honey Cups', cal: '350-420', price: 10 },
    { ar: 'حلي كاسات مانجو', en: 'Mango Cups', cal: '300-360', price: 10 },
    { ar: 'حلي كاسات رد فيلفيت', en: 'Red Velvet Cups', cal: '430-500', price: 10 },
  ],
};

const categories = [
  { key: 'hot',    label: 'مشروبات ساخنة', icon: '☕' },
  { key: 'cold',   label: 'مشروبات باردة', icon: '🧊' },
  { key: 'juices', label: 'عصائر',          icon: '🥤' },
  { key: 'soda',   label: 'مشروبات صودا',  icon: '🫧' },
  { key: 'sweets', label: 'حلويات',         icon: '🍰' },
];
