<?php
defined('NEJMT_ADMIN') or die('Direct access forbidden.');

// Copy this file to secret.php on the server and replace the placeholder
// with a hash generated by:
// php -r "echo password_hash('YourPassword', PASSWORD_BCRYPT, ['cost'=>12]);"
define('ADMIN_HASH', 'PLACEHOLDER_create_secret_php_on_server');
